name: Java App CI/CD with Sonar, Docker, AWS ECR, and Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCOUNT_ID: "637423236688"
      IMAGE_NAME: "spring"
      IMAGE_TAG: "${{ github.run_number }}"
      REPO_URI: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: SonarQube Scan
      run: mvn clean verify sonar:sonar -Dsonar.token=${SONAR_TOKEN} -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tektrio -Dsonar.projectKey=tektrio_customer2

    - name: Build Jar file
      run: mvn clean install

    - name: Build Docker image
      run: |
        docker build -t spring:${IMAGE_TAG} .
        echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

    - name: Push Docker image to AWS ECR
      run: |
        docker tag spring:${IMAGE_TAG} ${REPO_URI}
        docker push ${REPO_URI}

    - name: Set image using Kustomize
      run: |
         kustomize edit set image ${REPO_URI}

    - name: Apply Kubernetes manifests
      run: |
         kubectl apply -k .
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
